<?php
/* @var $this \Phavour\Runnable\View */
?>
<html>
    <head>
        <title>Welcome to Phavour!</title>
        <style>
        body{margin:0;padding:30px;font:14px/1.5 Helvetica,Arial,Verdana,sans-serif;}
        h1{margin:0 0 30px;font-size:40px;font-weight:normal;line-height:54px;border-bottom: 2px solid #CCCCCC;}
        a{color:#428bca;text-decoration:underline;}
        a:hover{color:#2a6496;}
        </style>
    </head>
    <body>
        <?php echo $this->content(); ?>
    </body>
</html>
